### ISSUE TITLE
Plugin in default package, needs to be moved to be used

### ISSUE THREAD

**Issue by Youcefhd13** [fiji/Multi_Kymograph#2]
I created a PR to package the plugin so I can use it in a plugin I'm making. Please let me know if further edits are needed.

http://forum.imagej.net/t/importing-classes-from-the-root-of-external-jars-jar-in-intellij-maven-project/4086

**Comment by ctrueden** [comment]
Great. Closing this issue in favor of #1, where we can continue to move forward.
